name: Automatic tests
on:
  release:
    types: [published]

jobs:
  test_and_build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        poetry-version: ["1.7.1"]
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run --all
      - name: Run tests
        run: poetry run pytest --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}

      - name: Build package
        run: poetry build
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Retrieve package artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.10
        with:
          name: release-dists
          path: dist/
