name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest --cov-report=term --cov-report=html

      - name: Prepare coverage dir
        run: |
          mkdir -p coverage/${{ matrix.python-version }}
          mv htmlcov/* coverage/${{ matrix.python-version }}/
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage/

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install pre-commit
        run: pip install pre-commit uv
      - name: Install dependencies
        run: uv sync --locked

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all

  build_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --locked --no-dev

      - name: Build package
        run: uv build

      - name: Upload package artifacts
        if: github.event_name == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  deploy_docs:
    if: |
      (github.event_name == 'push' && github.ref_name == 'main') ||
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - test_python
      - pre-commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv sync --locked

      - name: Download coverages
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: docs/htmlcov
          merge-multiple: true
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - run: uv run python docs/gen_badges.py
      - run: uv run python docs/gen_reference_code.py
      - run: uv run python docs/gen_reference_config.py
      - run: uv run typer b4_backup/__main__.py utils docs --name b4 --title "CLI reference" --output docs/reference/cli.md

      - name: Docs dry-run
        if: github.event_name == 'pull_request'
        run: uv run mkdocs build --strict
      - name: Deploy docs
        if: github.event_name == 'push' && github.ref_name == 'main'
        run: uv run mkdocs gh-deploy --force

  release_python:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs:
      - test_python
      - pre-commit
      - build_python
    environment:
      name: main
      url: https://pypi.org/p/b4-backup
    permissions:
      id-token: write
    steps:
      - name: Retrieve package artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1.10
